import { Inter } from "next/font/google";
import "./globals.css";
import PrivyWrapper from "@/privy/privyProvider";
import { FHEWrapper } from "@/fhevm/fheWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hidden Cards | Rivest | FHEVM | Inco Network",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PrivyWrapper>
          <FHEWrapper>{children}</FHEWrapper>
        </PrivyWrapper>
      </body>
    </html>
  );
}
